services:
  - type: web
    name: agri-smart-detect-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: VITE_BACKEND_URL
        value: https://agri-smart-detect-backend-3-m0y3.onrender.com
      - key: VITE_PLANT_ID_API_KEY
        sync: false
