services:
  - type: web
    name: agri-smart-detect-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://agri-smart-detect-backend.onrender.com
      - key: REACT_APP_PLANT_ID_API_KEY
        value: 8VY7pHmuqNXEt7WlEclcIazuj24GUivdJbSXxJXviDYGTuixpg